<?xml version="1.0"?>

<!-- This is the main structure of the robot. it has links, joints and material properties-->
<robot xmlns:xacro="http://ros.org/wiki/xacro">

  <!--xacro:property name="pi" value="3.14159" /-->

  <xacro:include filename="materials.xacro" />
  <xacro:include filename="robot_physical_properties.xacro" />
  <xacro:include filename="inertial_macros.xacro" />


  <link name="base_footprint">
  </link>

  <joint name="base_joint" type="fixed">
    <parent link="base_footprint" />
    <child link="bottom_link" />
    <origin xyz="0 0 0" rpy="0 0 0" />
  </joint>


  <!-- Bottom link of the robot -->
  <link name="bottom_link">
    <visual>
      <origin xyz="0 0 0" rpy="0 0 0"/>
      <geometry>
        <box size="${bottom_link_length} ${bottom_link_width} ${bottom_link_height}" />
      </geometry>
      <material name="grey"/>
    </visual>
    <collision>
      <geometry>
        <box size="${bottom_link_length} ${bottom_link_width} ${bottom_link_height}" />
      </geometry>
    </collision>
    <xacro:inertial_box mass="${bottom_link_mass}" x="${bottom_link_length}" y="${bottom_link_width}" z="${bottom_link_height}">
      <origin xyz="0 0 0" rpy="0 0 0"/>
    </xacro:inertial_box>
  </link>

  <link name="front_left_wheel_connector">
    <visual>
      <origin xyz="0 0 0" rpy="0 0 0" />
      <geometry>
        <cylinder radius="${wheel_connector_radius}" length="${wheel_connector_length}" />
      </geometry>
      <material name="red"/>
    </visual>
    <collision>
      <origin xyz="0 0 0" rpy="0 0 0" />
      <geometry>
        <cylinder radius="${wheel_connector_radius}" length="${wheel_connector_length}" />
      </geometry>
    </collision>
    <xacro:inertial_cylinder mass="${wheel_connector_mass}" length="${wheel_connector_length}" radius="${wheel_connector_radius}">
      <origin xyz="0 0 0" rpy="0 0 0"/>
    </xacro:inertial_cylinder>
  </link>

  <link name="front_right_wheel_connector">
    <visual>
      <origin xyz="0 0 0" rpy="0 0 0" />
      <geometry>
        <cylinder radius="${wheel_connector_radius}" length="${wheel_connector_length}" />
      </geometry>
      <material name="red"/>
    </visual>
    <collision>
      <origin xyz="0 0 0" rpy="0 0 0" />
      <geometry>
        <cylinder radius="${wheel_connector_radius}" length="${wheel_connector_length}" />
      </geometry>
    </collision>
    <xacro:inertial_cylinder mass="${wheel_connector_mass}" length="${wheel_connector_length}" radius="${wheel_connector_radius}">
      <origin xyz="0 0 0" rpy="0 0 0"/>
    </xacro:inertial_cylinder>
  </link>

  <link name="rear_left_wheel_connector">
    <visual>
      <origin xyz="0 0 0" rpy="0 0 0" />
      <geometry>
        <cylinder radius="${wheel_connector_radius}" length="${wheel_connector_length}" />
      </geometry>
      <material name="red"/>
    </visual>
    <collision>
      <origin xyz="0 0 0" rpy="0 0 0" />
      <geometry>
        <cylinder radius="${wheel_connector_radius}" length="${wheel_connector_length}" />
      </geometry>
    </collision>
    <xacro:inertial_cylinder mass="${wheel_connector_mass}" length="${wheel_connector_length}" radius="${wheel_connector_radius}">
      <origin xyz="0 0 0" rpy="0 0 0"/>
    </xacro:inertial_cylinder>
  </link>

  <link name="rear_right_wheel_connector">
    <visual>
      <origin xyz="0 0 0" rpy="0 0 0" />
      <geometry>
        <cylinder radius="${wheel_connector_radius}" length="${wheel_connector_length}" />
      </geometry>
      <material name="red"/>
    </visual>
    <collision>
      <origin xyz="0 0 0" rpy="0 0 0" />
      <geometry>
        <cylinder radius="${wheel_connector_radius}" length="${wheel_connector_length}" />
      </geometry>
    </collision>
    <xacro:inertial_cylinder mass="${wheel_connector_mass}" length="${wheel_connector_length}" radius="${wheel_connector_radius}">
      <origin xyz="0 0 0" rpy="0 0 0"/>
    </xacro:inertial_cylinder>
  </link>



  <!-- Front left wheel -->
  <link name="front_left_wheel_link">
    <visual>
      <origin xyz="0 0 0" rpy="0 0 0"/>
      <geometry>
        <cylinder radius="${wheel_radius}" length="${wheel_length}" />
      </geometry>
      <material name="black"/>
    </visual>
    <collision>
      <origin xyz="0 0 0" rpy="0 0 0"/>
      <geometry>
        <cylinder radius="${wheel_radius}" length="${wheel_length}" />
      </geometry>
    </collision>
    <xacro:inertial_cylinder mass="${wheel_mass}" length="${wheel_length}" radius="${wheel_radius}">
      <origin xyz="0 0 0" rpy="0 0 0"/>
    </xacro:inertial_cylinder>
  </link>

  <!-- Front left wheel steering -->
  <link name="front_left_steering_link">
    <visual>
      <origin xyz="0 0 0" rpy="0 0 0" />
      <geometry>
        <cylinder radius="0.001" length="0.01" />
      </geometry>
    </visual>
    <collision>
      <origin xyz="0 0 0" rpy="0 0 0" />
      <geometry>
        <cylinder radius="0.001" length="0.01" />
      </geometry>
    </collision>
    <xacro:inertial_cylinder mass="0.001" length="0.001" radius="0.01">
      <origin xyz="0 0 0" rpy="0 0 0"/>
    </xacro:inertial_cylinder>
  </link>


  <!-- Front right wheel -->
  <link name="front_right_wheel_link">
    <visual>
      <origin xyz="0 0 0" rpy="0 0 0"/>
      <geometry>
        <cylinder radius="${wheel_radius}" length="${wheel_length}" />
      </geometry>
      <material name="black"/>
    </visual>
    <collision>
      <origin xyz="0 0 0" rpy="0 0 0"/>
      <geometry>
        <cylinder radius="${wheel_radius}" length="${wheel_length}" />
      </geometry>
    </collision>
    <xacro:inertial_cylinder mass="${wheel_mass}" length="${wheel_length}" radius="${wheel_radius}">
      <origin xyz="0 0 0" rpy="0 0 0"/>
    </xacro:inertial_cylinder>
  </link>

  <!-- Front right wheel steering -->
  <link name="front_right_steering_link">
    <visual>
      <origin xyz="0 0 0" rpy="0 0 0" />
      <geometry>
        <cylinder radius="0.001" length="0.01" />
      </geometry>
    </visual>
    <collision>
      <origin xyz="0 0 0" rpy="0 0 0" />
      <geometry>
        <cylinder radius="0.001" length="0.01" />
      </geometry>
    </collision>
    <xacro:inertial_cylinder mass="0.001" length="0.001" radius="0.01">
      <origin xyz="0 0 0" rpy="0 0 0"/>
    </xacro:inertial_cylinder>
  </link>



  <!-- Rear Left Wheel-->
  <link name="rear_left_wheel_link">
    <visual>
      <origin xyz="0 0 0" rpy="0 0 0"/>
      <geometry>
        <cylinder radius="${wheel_radius}" length="${wheel_length}" />
      </geometry>
      <material name="black"/>
    </visual>
    <collision>
      <origin xyz="0 0 0" rpy="0 0 0"/>
      <geometry>
        <cylinder radius="${wheel_radius}" length="${wheel_length}" />
      </geometry>
    </collision>
    <xacro:inertial_cylinder mass="${wheel_mass}" length="${wheel_length}" radius="${wheel_radius}">
      <origin xyz="0 0 0" rpy="0 0 0"/>
    </xacro:inertial_cylinder>
  </link>



  <!-- Rear right wheel -->
  <link name="rear_right_wheel_link">
    <visual>
      <origin xyz="0 0 0" rpy="0 0 0"/>
      <geometry>
        <cylinder radius="${wheel_radius}" length="${wheel_length}" />
      </geometry>
      <material name="black"/>
    </visual>
    <collision>
      <origin xyz="0 0 0" rpy="0 0 0"/>
      <geometry>
        <cylinder radius="${wheel_radius}" length="${wheel_length}" />
      </geometry>
    </collision>
    <xacro:inertial_cylinder mass="${wheel_mass}" length="${wheel_length}" radius="${wheel_radius}">
      <origin xyz="0 0 0" rpy="0 0 0"/>
    </xacro:inertial_cylinder>
  </link>



  <!-- Bottom Joints-->

  <joint name="front_left_wheel_connector_joint" type="fixed">
    <parent link="bottom_link" />
    <child link="front_left_wheel_connector" />
    <origin xyz="${bottom_link_length/2-0.05} ${bottom_link_width/2} 0" rpy="-${3.1459/2} 0 0" />
  </joint>


  <joint name="front_left_steering_joint" type="revolute">
    <parent link="front_left_wheel_connector" />
    <child link="front_left_steering_link" />
    <origin xyz="0 0 ${wheel_connector_length/2}" rpy="0 0 0" />
    <axis xyz="0 1 0" />
    <limit lower="-1.0" upper="1.0" effort="100" velocity="100" />
  </joint>

  <joint name="front_left_wheel_joint" type="continuous">
    <parent link="front_left_steering_link" />
    <child link="front_left_wheel_link" />
    <origin xyz="0 0 0" rpy="0 0 0" />
    <axis xyz="0 0 1" />
    <limit effort="100" velocity="100" />
  </joint>

  <joint name="front_right_wheel_connector_joint" type="fixed">
    <parent link="bottom_link" />
    <child link="front_right_wheel_connector" />
    <origin xyz="${bottom_link_length/2-0.05} -${bottom_link_width/2} 0" rpy="-${3.1459/2} 0 0" />
  </joint>

  <joint name="front_right_steering_joint" type="revolute">
    <parent link="front_right_wheel_connector" />
    <child link="front_right_steering_link" />
    <origin xyz="0 0 -${wheel_connector_length/2}" rpy="0 0 0" />
    <axis xyz="0 1 0" />
    <limit lower="-1.0" upper="1.0" effort="100" velocity="100" />
  </joint>

  <joint name="front_right_wheel_joint" type="continuous">
    <parent link="front_right_steering_link" />
    <child link="front_right_wheel_link" />
    <origin xyz="0 0 0" rpy="0 0 0" />
    <axis xyz="0 0 1" />
    <limit effort="100" velocity="100" />
  </joint>


  <joint name="rear_left_wheel_connector_joint" type="fixed">
    <parent link="bottom_link" />
    <child link="rear_left_wheel_connector" />
    <origin xyz="-${bottom_link_length/2-0.05} ${bottom_link_width/2} 0" rpy="-${3.1459/2} 0 0" />
  </joint>

  <joint name="rear_right_wheel_connector_joint" type="fixed">
    <parent link="bottom_link" />
    <child link="rear_right_wheel_connector" />
    <origin xyz="-${bottom_link_length/2-0.05} -${bottom_link_width/2} 0" rpy="-${3.1459/2} 0 0" />
  </joint>


  <joint name="rear_left_wheel_joint" type="continuous">
    <parent link="rear_left_wheel_connector" />
    <child link="rear_left_wheel_link" />
    <origin xyz="0 0 ${wheel_connector_length/2}" rpy="0 0 0" />
    <axis xyz="0 0 1" />
    <limit effort="100" velocity="100" />
  </joint>


  <joint name="rear_right_wheel_joint" type="continuous">
    <parent link="rear_right_wheel_connector" />
    <child link="rear_right_wheel_link" />
    <origin xyz="0 0 -${wheel_connector_length/2}" rpy="0 0 0" />
    <axis xyz="0 0 1" />
    <limit effort="100" velocity="100" />
  </joint>




  <!-- -->
  <!-- -->
  <!-- TOP LINKS -->
  <link name="top_link">
    <visual>
      <origin xyz="0 0 0" rpy="0 0 0"/>
      <geometry>
        <box size="${top_link_length} ${top_link_width} ${top_link_height}" />
      </geometry>
      <material name="grey"/>
    </visual>
    <collision>
      <geometry>
        <box size="${top_link_length} ${top_link_width} ${top_link_height}" />
      </geometry>
    </collision>
    <xacro:inertial_box mass="${top_link_mass}" x="${top_link_length}" y="${top_link_width}" z="${top_link_height}">
      <origin xyz="0 0 0" rpy="0 0 0"/>
    </xacro:inertial_box>
  </link>


  <link name="front_left_to_top_connector">
    <visual>
      <origin xyz="0 0 ${bottom_to_top_connector_length/2}" rpy="0 0 0" />
      <geometry>
        <cylinder radius="${bottom_to_top_connector_radius}" length="${bottom_to_top_connector_length}" />
      </geometry>
      <material name="red"/>
    </visual>
    <collision>
      <origin xyz="0 0 ${bottom_to_top_connector_length/2}" rpy="0 0 0" />
      <geometry>
        <cylinder radius="${bottom_to_top_connector_radius}" length="${bottom_to_top_connector_length}" />
      </geometry>
    </collision>
    <xacro:inertial_cylinder mass="${bottom_to_top_connector_mass}" length="${bottom_to_top_connector_length}" radius="${bottom_to_top_connector_radius}">
      <origin xyz="0 0 0" rpy="0 0 0"/>
    </xacro:inertial_cylinder>
  </link>

  <link name="front_right_to_top_connector">
    <visual>
      <origin xyz="0 0 ${bottom_to_top_connector_length/2}" rpy="0 0 0" />
      <geometry>
        <cylinder radius="${bottom_to_top_connector_radius}" length="${bottom_to_top_connector_length}" />
      </geometry>
      <material name="red"/>
    </visual>
    <collision>
      <origin xyz="0 0 ${bottom_to_top_connector_length/2}" rpy="0 0 0" />
      <geometry>
        <cylinder radius="${bottom_to_top_connector_radius}" length="${bottom_to_top_connector_length}" />
      </geometry>
    </collision>
    <xacro:inertial_cylinder mass="${bottom_to_top_connector_mass}" length="${bottom_to_top_connector_length}" radius="${bottom_to_top_connector_radius}">
      <origin xyz="0 0 0" rpy="0 0 0"/>
    </xacro:inertial_cylinder>
  </link>

  <link name="rear_left_to_top_connector">
    <visual>
      <origin xyz="0 0 ${bottom_to_top_connector_length/2}" rpy="0 0 0" />
      <geometry>
        <cylinder radius="${bottom_to_top_connector_radius}" length="${bottom_to_top_connector_length}" />
      </geometry>
      <material name="red"/>
    </visual>
    <collision>
      <origin xyz="0 0 ${bottom_to_top_connector_length/2}" rpy="0 0 0" />
      <geometry>
        <cylinder radius="${bottom_to_top_connector_radius}" length="${bottom_to_top_connector_length}" />
      </geometry>
    </collision>
    <xacro:inertial_cylinder mass="${bottom_to_top_connector_mass}" length="${bottom_to_top_connector_length}" radius="${bottom_to_top_connector_radius}">
      <origin xyz="0 0 0" rpy="0 0 0"/>
    </xacro:inertial_cylinder>
  </link>

  <link name="rear_right_to_top_connector">
    <visual>
      <origin xyz="0 0 ${bottom_to_top_connector_length/2}" rpy="0 0 0" />
      <geometry>
        <cylinder radius="${bottom_to_top_connector_radius}" length="${bottom_to_top_connector_length}" />
      </geometry>
      <material name="red"/>
    </visual>
    <collision>
      <origin xyz="0 0 ${bottom_to_top_connector_length/2}" rpy="0 0 0" />
      <geometry>
        <cylinder radius="${bottom_to_top_connector_radius}" length="${bottom_to_top_connector_length}" />
      </geometry>
    </collision>
    <xacro:inertial_cylinder mass="${bottom_to_top_connector_mass}" length="${bottom_to_top_connector_length}" radius="${bottom_to_top_connector_radius}">
      <origin xyz="0 0 0" rpy="0 0 0"/>
    </xacro:inertial_cylinder>
  </link>

  <!--TOP JOINTS-->
  <joint name="front_left_bottom_joint" type="fixed">
    <parent link="bottom_link" />
    <child link="front_left_to_top_connector" />
    <origin xyz="${bottom_link_length/2-0.05} ${bottom_link_width/2-0.05} 0" rpy="0 0 0" />
  </joint>

  <joint name="front_right_bottom_joint" type="fixed">
    <parent link="bottom_link" />
    <child link="front_right_to_top_connector" />
    <origin xyz="${bottom_link_length/2-0.05} -${bottom_link_width/2-0.05} 0" rpy="0 0 0" />
  </joint>

  <joint name="rear_left_bottom_joint" type="fixed">
    <parent link="bottom_link" />
    <child link="rear_left_to_top_connector" />
    <origin xyz="-${bottom_link_length/2-0.05} ${bottom_link_width/2-0.05} 0" rpy="0 0 0" />
  </joint>

  <joint name="rear_right_bottom_joint" type="fixed">
    <parent link="bottom_link" />
    <child link="rear_right_to_top_connector" />
    <origin xyz="-${bottom_link_length/2-0.05} -${bottom_link_width/2-0.05} 0" rpy="0 0 0" />
  </joint>

  <joint name="front_left_top_joint" type="fixed">
    <parent link="front_left_to_top_connector" />
    <child link="top_link" />
    <origin xyz="-${top_link_length/2-0.05} -${bottom_link_width/2-0.05} ${bottom_to_top_connector_length}" rpy="0 0 0" />
  </joint>

  <!-- <joint name="front_right_top_joint" type="fixed">
    <parent link="front_right_to_top_connector" />
    <child link="top_link" />
    <origin xyz="0 0 ${bottom_to_top_connector_length}" rpy="0 0 0" />
  </joint> -->

</robot>