controller_manager:
  ros__parameters:
    update_rate: 100 # Hz

    rear_velocity_controller:
      type: forward_command_controller/ForwardCommandController

    front_steering_controller:
      type: forward_command_controller/ForwardCommandController

    joint_state_broadcaster:
      type: joint_state_broadcaster/JointStateBroadcaster

rear_velocity_controller:
  ros__parameters:
    joints:
      - rear_left_wheel_joint
      - rear_right_wheel_joint

front_steering_controller:
  ros__parameters:
    joints:
      - front_left_steering_joint
      - front_right_steering_joint
